spring:
  datasource:
    name: software_engineering

    generate-unique-name: false

    driver-class-name: com.mysql.cj.jdbc.Driver

    url: jdbc:mysql://106.14.97.109/software_engineering
    username: se
    password: 123456


